### ISSUE TITLE
tests: `make test` fails if `make check` was not run

### ISSUE THREAD

**Issue by rnsanchez** [beached/daw_json_link#108]
Possibly a dependency-chain omission, but it was necessary to explicitly run `make check` in order for `make test` to work.

To reproduce, it was enough to run `make clean` and then `make test` will fail, as it does not find the necessary binaries to run.

**Comment by beached** [comment]
Just waiting to make sure tests run and should be fixed.  I had an exclude from all in the past to speed up edit/debug.  But it's no longer needed. https://github.com/beached/daw_json_link/pull/109

**Comment by beached** [comment]
#109 should fix this.

**Comment by rnsanchez** [comment]
Maybe this is a minor issue on my side?

Trying on a fresh clone (9df37c1f6ffa7e42f8d872c19698d96ea6aa1b40):

    $ cmake CMakeLists.txt
    $ make test
    ...
    Unable to find executable: /home/rnsanchez/apps/daw_json_link/stream_output_test_bin
    47/47 Test #47: stream_output_test ..........................***Not Run   0.00 sec
    
    0% tests passed, 47 tests failed out of 47

But:

    $ make check
    ...
    47/47 Test #47: stream_output_test ..........................   Passed    0.00 sec
    
    100% tests passed, 0 tests failed out of 47
    
    Total Test time (real) =  31.72 sec
    [100%] Built target check

Then:

     $ make test
    Running tests...
    Test project /home/rnsanchez/apps/daw_json_link
    ...
    100% tests passed, 0 tests failed out of 47
    
    Total Test time (real) =  31.45 sec

Let me know if this is a real issue.

**Comment by beached** [comment]
It is my understanding that cmake requires `make` first, prior to calling make test or ctest

**Comment by rnsanchez** [comment]
So maybe this is not an issue anymore.
Unless you have reasons to keep this open, I'm OK with closing it.

**Comment by rnsanchez** [comment]
OK I think I understand now (not versed enough with `cmake`).

Here's `test`:

    # Special rule for the target test
    test:
            @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
            /usr/bin/ctest --force-new-ctest-process $(ARGS)
    .PHONY : test

Here's `check`:

    # Build rule for target.
    check: cmake_check_build_system
            $(MAKE) -f CMakeFiles/Makefile2 check
    .PHONY : check

As it can be seen, `check` implies in `cmake_check_build_system` as a dependency, which is what triggers building (that's why `make check` "works", as it builds prerequisites, whereas `make test` fails for trying to run things that have not been built yet):

    # Special rule to run CMake to check the build system integrity.
    # No rule that depends on this can have commands that come from listfiles
    # because they might be regenerated.
    cmake_check_build_system:
            $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
    .PHONY : cmake_check_build_system

It seems that `test` is some automatic rule created by `cmake`.  From `CMakeList.txt`, it seems that you explicitly create `check`.  I thought (naïvely) that simply adding the dependency could fix, but `cmake` complained a lot.  So, yes, I'm not versed enough with `cmake`, and am possibly too used to have used `make test` throughout the decades.

This now feels like a non-issue.  Apologies for all the noise.

**Comment by beached** [comment]
I had a solution for this.  Sorry.  instead of make test, make check.  I had created that target for this purpose.  It will depend on the target full(all the tests already do) and then run the test command.  So the steps are 
`cmake ..` or if you do inplace `cmake .`
`make check`
