### ISSUE TITLE
Rename JSON variable

### ISSUE THREAD

**Issue by t0mpl** [beached/daw_json_link#163]
Hello, 
thank for the library which works perfectly, i was wondering : 
is there anyway to map struct member to json property?
example: 
json { ts: 45435235 } to struct { dateCreated: 45435235 }

**Comment by beached** [comment]
There is no req that the names match.  You are mapping JSON members to the classes constructor.   https://github.com/beached/daw_json_link/blob/release/cookbook/class.md shows the class with member_0 and JSON “member0”
