### ISSUE TITLE
 ‘const daw::json::json_name<1>’ is not derived from ‘const std::shared_ptr<_Tp>’

### ISSUE THREAD

**Issue by t0mpl** [beached/daw_json_link#166]
Hi again,

when trying to build my code, i got a really verbose error that I can't past entirely, it told me first some about pedantic (which i disabled), then i got a much bigger one that i paste here:

`/usr/include/c++/9/bits/shared_ptr.h:388:5: note:   template argument deduction/substitution failed:
In file included from /home/tom/Projects/cproject/build/_deps/daw_json_link-src/include/daw/json/impl/daw_json_parse_policy.h:12,
                 from /home/tom/Projects/cproject/build/_deps/daw_json_link-src/include/daw/json/impl/daw_json_iterator_range.h:11,
                 from /home/tom/Projects/cproject/build/_deps/daw_json_link-src/include/daw/json/daw_json_link.h:11,
                 from /home/tom/Projects/cproject/app/main.cpp:29:
/home/tom/Projects/cproject/build/_deps/daw_json_link-src/include/daw/json/impl/daw_json_parse_common.h:265:56: note:   ‘const string_view’ {aka ‘const daw::basic_string_view<char>’} is not derived from ‘const std::shared_ptr<_Tp>’
  265 |  inline constexpr bool is_no_name = ( JsonMember::name == no_name );
      |                                     ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
In file included from /usr/include/c++/9/memory:81,
                 from /usr/local/include/boost/system/detail/std_interoperability.hpp:12,
                 from /usr/local/include/boost/system/error_code.hpp:963,
                 from /usr/local/include/boost/beast/core/error.hpp:14,
                 from /usr/local/include/boost/beast/core/detail/bind_handler.hpp:13,
                 from /usr/local/include/boost/beast/core/bind_handler.hpp:14,
                 from /usr/local/include/boost/beast/core/async_base.hpp:14,
                 from /usr/local/include/boost/beast/core.hpp:15,
                 from /home/tom/Projects/cproject/app/main.cpp:19:
/usr/include/c++/9/bits/shared_ptr.h:393:5: note: candidate: ‘template<class _Tp> bool std::operator==(std::nullptr_t, const std::shared_ptr<_Tp>&)’
  393 |     operator==(nullptr_t, const shared_ptr<_Tp>& __a) noexcept
      |     ^~~~~~~~`

any idea what is happening here? 

(here is my code)
`
struct WeatherUpdate
{
  string type;      // e

};

namespace daw::json
{
  template <>
  struct json_data_contract<WeatherUpdate>
  {
    using type = json_member_list<
        json_string<"e">>;
  };
} `

**Comment by beached** [comment]
So first, the code you have here needs CNTTP from C++20.  But it is missing the specialization of json_data_contract.  If using C++20 I would have the following for the mapping 

```

namespace daw::json {
  template <>
  struct json_data_contrac<WeatherUpdate> {
    using type = json_member_list<json_string<"e">>;
  };
}

```
If C++17 or 20

```
namespace daw::json {
  template <>
  struct json_data_contrac<WeatherUpdate> {
     static constexpr char const mem_e[] = "e";
    using type = json_member_list<json_string<mem_e>>;
  };
}

```

**Comment by t0mpl** [comment]
thanks for your help, i still get an error " error: non-constant condition for static assertion

`/home/tom/Projects/cproject/app/main.cpp:198:77:   required from here
/home/tom/Projects/cproject/build/_deps/daw_json_link-src/include/daw/json/impl/daw_json_link_impl.h:341:18: error: non-constant condition for static assertion
  341 |   static_assert( not is_no_name<JsonMember>,`

I've checked my code many times but dont have a clue, any idea?

**Comment by beached** [comment]
Do you have a link to a repo that shows this?  Also, what compiler/environment?

**Comment by beached** [comment]
OK, I have replicated it.  gcc 9's c++20 support isn't there yet and causing it.  
I have an option exposed in cmake `DAW_JSON_NO_CPP_NAMES` that will allow for C++20 support while disabling the naming.  The other option is to compile in C++17 mode.

The result is that the naming must use the C++17 method or g++10 can be used to get support.  This is the risk of C++20 these days.  Just waiting for the CI to verify I didn't break anything with the option and it will be in release

**Comment by t0mpl** [comment]
i've downloaded the last release and put my c++ to version 17 while waiting for GNU 10 on my linux distribution, and i can compile.
Thank you very much.
