### ISSUE TITLE
CBOR support

### ISSUE THREAD

**Issue by ArtisticCoding** [beached/daw_json_link#200]
Any plan to support CBOR(RFC 8949)?

I think that if daw_json_link support CBOR, daw_json_link will be best C++ serialization/reflection library!!!

**Comment by beached** [comment]
It's not something I can personally implement in the near future.  But with the current architecture being as it is, the logical place might be to do the data conversion by converting the data from CBOR->JSON for input and JSON->CBOR for output.  There are tools like tinycbor https://github.com/intel/tinycbor/tree/master/tools that have converters. 

But the way the library is architected, you are building custom JSON parsers for your data types, not a single JSON parser for a DOM type.  This comes with a cost like where the data format is coupled to the library.  This is seen in some of the data mapping options.  A library that does a similar approach for CBOR seems like a good idea though, it's just not something I need in foreseeable future.

**Comment by ArtisticCoding** [comment]
Thanks for the reply. I will personally implement it.

**Comment by beached** [comment]
That would be really neat.  I think the model for doing the mappings is sound.  Even if we get static reflection, it provides the types to map to over it.

Right now I am working on JSON Schema -> Bindings for the library and a JSON RPC server that uses it to do the serialization/deserialization transparently.  That will keep me busy.
