### ISSUE TITLE
Possible optimization in parsing whitespaces

### ISSUE THREAD

**Issue by kostya** [beached/daw_json_link#225]
for this: https://github.com/kostya/benchmarks#json, i increased file size by 5 times and test with and without whitespaced json.

with whitespaces:
|parser|time|memory|
|-|-|-|
|C++/g++ (simdjson On-Demand)|0.788|1756 Mb|
|C++/g++ (DAW JSON Link)|0.929|1123 Mb|

without whitespaces:
|parser|time|memory|
|-|-|-|
|C++/g++ (DAW JSON Link)|0.609|607 Mb|
|C++/g++ (simdjson On-Demand)|0.725|1239 Mb|

looks like whitespaces process not effective.

**Comment by beached** [comment]
Looking into it, I am constrained by the library being constexpr and luckily real world JSON that are not config files are minimized.

Is the new test data generator in the benchmark repos?

**Comment by kostya** [comment]
i change number in generator to 5_524_288, and switch between `pretty_generate` and `generate`

**Comment by beached** [comment]
I am unsure of an approach that works at the moment that doesn't sacrifice minimized JSON performance.  Seeing as most JSON is minimized that is the primary goal of this.  I could put it behind a parse flag, but the difference so far I was able to get is a few percentage and depends on architecture as on macOS I am seeing it faster already.

Even the non-minified JSON I have been looking at often doesn't have more than 2-3 spaces between items.

**Comment by kostya** [comment]
yes may be this is not real world use case.
