### ISSUE TITLE
Installer in 2.9.3 may be broken.

### ISSUE THREAD

**Issue by toge** [beached/daw_json_link#232]
In 2.9.3, cmake installer creates such directories.
I think it is a CMakeLists.txt bug in 2.9.3.

```
include/
├── daw
│   ├── impl
│   ├── iterator
│   └── utf_range
├── include
│   ├── daw
│   │   └── json
│   │       └── impl
│   └── third_party
│       └── dragonbox
└── utf8
```

For example:
In 2.9.2, cmake installer create such directories.

```
include/
├── daw
│   ├── impl
│   ├── iterator
│   ├── json
│   │   └── impl
│   └── utf_range
├── third_party
│   └── dragonbox
└── utf8
```

## reproduction methods

```
wget -nd https://github.com/beached/daw_json_link/archive/refs/tags/v2.9.3.zip
unzip v2.9.3.zip
cd daw_json_link-2.9.3/
cmake -B build -S .
mkdir /tmp/dummy
cmake --install build  --prefix /tmp/dummy/
cd /tmp/dummy
tree -d include/
```

**Comment by beached** [comment]
I am not seeing the issue, it installs the library to ${prefix}/include and those files are the library.  It's a header only library.

**Comment by beached** [comment]
Thanks, I made a change to how it works and forgot the `/` after the folder name.  Fixed with https://github.com/beached/daw_json_link/pull/233

**Comment by beached** [comment]
https://github.com/beached/daw_json_link/releases/tag/v2.9.4

**Comment by toge** [comment]
Thank you for your quick response!
I confirmed it.
