### ISSUE TITLE
Wrong json_linkConfig.cmake install dir?

### ISSUE THREAD

**Issue by kerero** [beached/daw_json_link#238]
`cmake --build . --target install` installs

* `/usr/local/share/json_link/cmake$/json_linkConfig.cmake`
* `/usr/local/share/json_link/cmake$/json_linkConfigVersion.cmake`

in `/usr/local/share/json_link/cmake$` instead of `/usr/local/share/json_link/cmake`?

cmake version 3.18.4

**Comment by beached** [comment]
Thanks, investigating

**Comment by beached** [comment]
Fixed with https://github.com/beached/daw_json_link/pull/252
