### ISSUE TITLE
Vcpkg port in progress

### ISSUE THREAD

**Issue by mheyman** [beached/daw_json_link#247]
I'm trying to get *daw_json_link* into vcpkg to make it easier to use. See https://github.com/microsoft/vcpkg/pull/18411

If you are not familiar with vcpkg, it makes it almost rust-simple to include dependencies in your CMake build (you need to have a manifest file holding your program's dependencies and use the vcpkg build tooling) but it does have some quirks. One of the quirks is that the port names must be lower case and cannot have underscores. Another is that when trying your best to build across multiple architectures, you sometimes run into incompatibilities that you don't expect.

So, the first change is the name of the package you use with CMake's `find_package()`. They are changed to `daw::daw-header-libraries`, `daw::daw-utf-range`, and `daw::daw-json-link`. I *think* I could have kept the same CMake package names but this was easier (because of some vcpkg-related automated CMake package fixup). Plus this style is more expected for vcpkg ports ;-)

The way vpkg builds work, I had to actually make 3 ports, [daw-header-libraries](https://github.com/mheyman/vcpkg/tree/master/ports/daw-header-libraries), [daw-utf-range](https://github.com/mheyman/vcpkg/tree/master/ports/daw-utf-range), and [daw-json-link](https://github.com/mheyman/vcpkg/tree/master/ports/daw-json-link) with the proper dependencies...The vcpkg automated build system didn't like CMake's `FetchContent_Declare()` on, I think, Linux.  So, I patched those calls out of the build and used vcpkg's dependency mechanism to get the same results.

The last issues I ran into was that utf_range includes source from the same place as the vcpkg [utfcpp](https://github.com/microsoft/vcpkg/tree/master/ports/utfcpp) port. To ameliorate any conflicts that could arise from somebody wanting both daw-json-link and utfcpp, I moved the `utf8` namespace *daw_json_link* uses under `daw::utf8` and also moved the files under the `include/daw` directory.

Vcpkg doesn't have dragonbox yet so I left that as it was but perhaps I shouldn't have...

You can take a look at the patch files in the 3 port directories I linked in this message to see the changes.

Thanks for a stellar JSON library - I cannot wait to see what you do with reflection :-)

**Comment by beached** [comment]
So I have updated utf_range to move fall under the daw folder with https://github.com/beached/utf_range/commit/1fb3c007ad164d1d30d560b4ce08bbaa68b7fa55

json link updates to use that with c0b1f9f5e23b8c59a20ce54a80283b15f35a81a6

Since I have modified dragonbox quite a bit and plan to use a new to_chars optimized for JSON, I will move that under the daw folder too to prevent collisions

**Comment by beached** [comment]
One concern, the change in project name and alias is a breaking change for existing users who are using FetchContent and target_link_libraries( ... daw::json_link )

What I will do is add an option for when using package management so the the sub_directory( extern ) is excluded.

**Comment by beached** [comment]
I think in v3 when it is released I can change the names in the project to use - instead of _ as there is an API break happening already.  But prior to that it is a concern, unless we can make both work(another ALIAS maybe?) as I would prefer not to break existing code.

**Comment by beached** [comment]
https://github.com/beached/daw_json_link/tree/v2.9.7 of the release branch has much of the changes.   The namespace changes where utf8:: was called should be fine as it walks up the namespaces to find the closest name and the code is already under ::daw

**Comment by beached** [comment]
If you set the option -DDAW_ENABLE_PACKAGE_MANAGEMENT=ON it will exclude the sub_directory( extern )

**Comment by beached** [comment]
In v3 when released I can do the _ to - changes and just add another add_library with an alias to the old names.  On the dependencies I can do that sooner as they have a less rigorous release cycle

**Comment by beached** [comment]
Header libraries should have the changes in the patch folder, unless I made a mistake.  Including name changes.  I was able to keep the alias library daw::header_libraries 
https://github.com/beached/header_libraries/releases/tag/v.1.21.0

**Comment by beached** [comment]
Utf Range should have the changes, including name changes while retaining the old library alias too https://github.com/beached/utf_range/releases/tag/v2.1.0

**Comment by beached** [comment]
JSON Link Release should have the changes needed in the repos now too https://github.com/beached/daw_json_link/releases/tag/v2.9.8

**Comment by beached** [comment]
I don't know much about vcpkg, have used it, but I saw you specified DAW_ENABLE_TESTING=OFF, that should be the default, but adding DAW_USE_PACKAGE_MANAGEMENT=ON it will not do the add_subdirectory( extern )

**Comment by beached** [comment]
Was there anything else that may need changing to fit.  My only concern generally is that it doesn't change my dev process, this seems to be fine that way :) and that breaking changes are minimized or put into the next release.  So far so good, I think

**Comment by mheyman** [comment]
Those changes rock. I've just updated the pull request to vcpkg.

FYI: To verify the daw-json-link port works, I pulled the daw_json_link unit tests out into a separate build that depends on vcpkg ports and placed that build [here](https://github.com/mheyman/daw_json_link_vcpkg_tests). Of course, until that `daw-json-link` port gets accepted, that repository isn't too useful to anybody but me ;-)

**Comment by beached** [comment]
If I did a similar change to the tests and exclude extern/ sub directory when DAW_USE_PACKAGE_MANAGEMENT=ON, would that help?

**Comment by beached** [comment]
FYI: The current release tag is v2.9.11 d8cb3a25a545b27b6ab5e68f4480b92ad0dc78fe 

At this time, I don't see more into release for a bit.

**Comment by beached** [comment]
Awesome, looks like it was merged 🎉
