### ISSUE TITLE
CMake outputs to stderr

### ISSUE THREAD

**Issue by apmorton** [beached/daw_json_link#269]
https://github.com/beached/daw_json_link/blob/c18b180b6bec396be9e58e480fa23163db3d42f9/CMakeLists.txt#L42 (and other usages of `message` default to `NOTICE`, which outputs to stderr.

For us over at compiler explorer this causes our cron job to detect failure and email us, since any stderr output is considered an error by chronic.

It would be helpful if all these status-like outputs in your cmake scripts could be prefixed with `STATUS`, like such:
```
message(STATUS "DAW_JSON_NO_CONST_EXPR=ON: Guaranteed copy elision in class/array types is ON")
```

**Comment by beached** [comment]
This should be fixed in https://github.com/beached/daw_json_link/releases/tag/v2.11.2 
I checked the dependencies and they do not utilize cmake message.  The develop branch will have this upon the next commit

**Comment by beached** [comment]
Fixed in develop too.
