### ISSUE TITLE
Update NTTP detection macros

### ISSUE THREAD

**Issue by technic** [beached/daw_json_link#273]
Use `__cpp_nontype_template_args` instead of `__cpp_nontype_template_parameter_class`

see also here https://github.com/foonathan/lexy/issues/15

**Comment by beached** [comment]
Should be fixed via b90116a13ca3e2ce37e6890b309d1fd2c1979ae3 for release.  Just waiting on CI to confirm no mistakes/typos

**Comment by beached** [comment]
Also, fixed in v3 branch via 75957acaa0136da8fb654b0a78960d8f46f5a6a2
