### ISSUE TITLE
The cookbook for Variants is still broken

### ISSUE THREAD

**Issue by jk-jeon** [beached/daw_json_link#295]
Hi,

In [this](https://github.com/beached/daw_json_link/blob/v3/docs/cookbook/variant.md) page most of the code snippets show nothing.

I mean, I know it is fixed in the develop branch, but wouldn't it be better to be fixed in the release branch as well?

**Comment by beached** [comment]
thanks.  Develop isn't in use anymore and v3 is the current dev until it leaves beta.  but I must have mixed fixing in both last time :(

**Comment by beached** [comment]
Should be fixed with #294

**Comment by beached** [comment]
Thanks for pointing that out.  I have a bunch of docs to update for the v3 release which is beta now, the latest release, v2.9.11 has the correct docs too.
