### ISSUE TITLE
Seg fault with std::optional<bool> and std::variant

### ISSUE THREAD

**Issue by marcelomatus** [beached/daw_json_link#359]
Hi,
Thanks for the quick fix in the previous case 357.

Here is a little variant of issue 357. When you have an std::optional<bool> member before a std::variant, it produces a seg fault when parsing.

struct buses_res {
        int uid{ };
        std::optional< bool > active;  /* here is the problem */
        std::variant<int, std::string> id;
        std::optional<double> volts;
};

If you change active to std::optional<int>, it works.

Attached is a test file case based on the issue_357_test.cpp.

Thanks!

[issue_357b_test.cpp.zip](https://github.com/beached/daw_json_link/files/10119205/issue_357b_test.cpp.zip)

**Comment by beached** [comment]
Is it just a json_variant mapping that uses that it is a string/int to determine the alternative to construct? Or is it tagged?

**Comment by marcelomatus** [comment]
Sorry, it is not clear in the post:

If you change active from std::optional< bool > to std::optional< int >, it works.

**Comment by marcelomatus** [comment]
Is just a member variant with the name "id"; no other tags are involved.

**Comment by marcelomatus** [comment]
Sorry, two errors occur. When "active" shows up once as in the file I uploaded, there is a seg fault probably due to a mismatch between the 'bool' type and the integer value in the input data "active':1.
 
If you remove both "active" fields in the input, there is a second error  that says

  what():  Unexpected character data at start of value

just before aborting.

**Comment by beached** [comment]
I am seeing it trying to part 1 as a json bool and throwing an exception because it is not `true` or `false`.  I think what you want is `json_number_number<id, std::optional<bool>>` for that mapping. 

However, this found a bug in the arith traits `make_unsigned_t<bool>` as it wasn't specialized.  Fixing that and I tested the code with that and it works.  Alternatively using true/false for active works now.  Nice find.

**Comment by beached** [comment]
Looking into the second.

**Comment by marcelomatus** [comment]
This is the second error when no "active" field is present

[issue_357c_test.cpp.zip](https://github.com/beached/daw_json_link/files/10119404/issue_357c_test.cpp.zip)

**Comment by marcelomatus** [comment]
In the second case, when "active" is not present, it doesn't matter the std::optional type; it fails for optional bool and optional int.

**Comment by beached** [comment]
I'm working on a fix.  The issue is related to the first one when a member is skipped to be parsed later, strings are recorded at 1 past the quote because we already know it is a string.  That comes up here because it is deducing the type but the quotes are missing.
