### ISSUE TITLE
Misspelled or unknown field names... how to detect them?

### ISSUE THREAD

**Issue by marcelomatus** [beached/daw_json_link#370]
Hi!
Is there a parse option to detect unknown or misspelled field names?

For example, if I am expecting:

struct Foo {
   std::optional< int > bar;
};

But in the JSON file it says

  "foo":  {"barr": 3}

ie, there is a misspelled/unknown "barr" member name.

Thanks!

**Comment by beached** [comment]
One can require that the mapping maps all members of a class for either the default for all classes or for individual classes. 

This was undocumented and a bug in the docs.  I have fixed the documentation in `docs/cookbook/parser_policies.md` and added `docs/cookbook/exact_class_mappings.md`.  I also added the example in `tests/src/issue_370_exact_class_mapping_test.cpp`.

I think this should help, and thanks for asking, it helped me find a bug in my documentation and testing.

**Comment by marcelomatus** [comment]
Thanks!, it worked
