### ISSUE TITLE
TemporarilyMutateBuffer::yes produces a compilation error

### ISSUE THREAD

**Issue by marcelomatus** [beached/daw_json_link#372]
Using parser flag  daw::json::options::TemporarilyMutateBuffer::yes produces the following error:

'''
/usr/local/include/daw/json/daw_from_json.h:69:48: error: invalid conversion from ‘const char*’ to ‘daw::json::v3_12_0d::BasicParsePolicy<3348, daw::json::v3_12_0d::json_detail\
s::NoAllocator>::iterator’ {aka ‘char*’} [-fpermissive]
   69 |                           ParseState( std::data( json_data ), daw::data_end( json_data ) );
      |                                       ~~~~~~~~~^~~~~~~~~~~~~
      |                                                |
      |                                                const char*

'''

it seems std::data returns 'const char*' while daw::data_end returns 'char*', and ParseState expects 'char*' for both parameters.

**Comment by beached** [comment]
What version are you using?  This feels like an older bug.  Do you have an example that replicates the issue?

**Comment by marcelomatus** [comment]
I am using the latest github's pull.

You can use the same issue_370 as an example, adding the TemporarilyMutateBuffer option to the parser:

...

int main( ) {
        bool error1_found = false;
        namespace opt = daw::json::options;
        try {
                // Any extra member is an error globally
                auto f = daw::json::from_json<Foo>(
                  json_doc1,
                  opt::parse_flags<opt::UseExactMappingsByDefault::yes,
                                   daw::json::options::TemporarilyMutateBuffer::yes> );
                (void)f;
        } catch( daw::json::json_exception const & ) { error1_found = true; }
        ensure( error1_found );

....

**Comment by beached** [comment]
Thanks, I thought I disabled that fully and was going to remove it in the next version.  It wasn't fruitful and resulted in slower codegen.  I'll fix the error though, it should have worked, but done nothing

**Comment by marcelomatus** [comment]
perfect, thanks!
