### ISSUE TITLE
Json Value parsing doesn't resolve escaped paths

### ISSUE THREAD

**Issue by MartinTheDragon** [beached/daw_json_link#399]
The following doesn't seem to work.

```c++
using namespace daw::json;
using std::string;

json_value json{R"({"example.com":"justanormalstring"})"};
string& parsed_value = as<string>(json["example\\.com"]); // R"(example\.com)" also doesn't work
```

The code for escape sequences like this seems to be there, but it doesn't work either way.
Also, this example currently produces a segmentation fault, as mentioned in #398.

**Comment by beached** [comment]
Fixed by #400

**Comment by beached** [comment]
This is fixed by #400

**Comment by beached** [comment]
Thanks for finding these issues

**Comment by MartinTheDragon** [comment]
Thanks for fixing them!
