### ISSUE TITLE
lack of  daw/daw_constant.h

### ISSUE THREAD

**Issue by toge** [beached/daw_json_link#419]
There are not daw/daw_constant.h.

I met a compilation error on daw_json_link/3.23.1.
```
In file included from include/daw/json/impl/daw_json_link_types_fwd.h:13,
                 from include/daw/json/daw_from_json_fwd.h:13,
                 from include/daw/json/daw_from_json.h:13,
                 from include/daw/json/daw_json_link.h:13,
                 from test_package.cpp:4:
include/daw/json/impl/daw_json_enums.h:13:10: fatal error: daw/daw_constant.h: No such file or directory
   13 | #include <daw/daw_constant.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

It seems to be lack of daw/daw_constants.h which should be included header_libraries.
Are there any plan to upgrade header_libraries?

**Comment by beached** [comment]
Sorry, that was a timing thing last night.  Should be fixed now if you are pulling from source(may need to update).  I had to merge the header libraries PR.   If it is from a package manager I am unsure how long they will take to update(there are PR's for vcpkg)

**Comment by beached** [comment]
Should be good 
https://github.com/beached/header_libraries/releases/tag/v2.101.0
https://github.com/beached/daw_json_link/releases/tag/v3.23.2

Thanks for reporting.

**Comment by toge** [comment]
@beached 
Thanks a lot!
