### ISSUE TITLE
daw_is_detected

### ISSUE THREAD

**Issue by iwasz** [beached/daw_json_link#423]
Hey

  Today I hit "clean rebuild" (which pulls daw_json_link repos from scratch) in my project and encountered an error (`error: ‘is_detected_v’ was not declared in this scope`) which I resolved adding `#include <daw/daw_is_detected.h>` to the `build/_deps/daw_json_link-src/include/daw/json/concepts/daw_nullable_value_fwd.h`. I add the library to my CMakeLists as such:

```
CPMAddPackage (
    NAME daw_json_link
    GITHUB_REPOSITORY beached/daw_json_link
    VERSION 3.23.2
)

add_definitions(-DDAW_JSON_NO_DEFAULT_OSTREAM_WRITER)
add_definitions(-DDAW_JSON_NO_DEFAULT_CSTDIO_WRITER)
include_directories(${daw_json_link_SOURCE_DIR}/include)
include_directories(${daw_json_link_SOURCE_DIR}/../daw_header_libraries-src/include)
include_directories(${daw_json_link_SOURCE_DIR}/../daw_utf_range-src/include)
```

**Comment by beached** [comment]
There's a bug in how it pulls in the deps, it was pulling the dev branch and not the release from header_libraries.  I'm pushing a fix to json link's `release` branch

**Comment by beached** [comment]
Fixed by https://github.com/beached/daw_json_link/releases/tag/v3.23.3

**Comment by beached** [comment]
Thanks for reporting.  The changes should not have made it to you yet.
