### ISSUE TITLE
Is there an adl_serializer equivalent?

### ISSUE THREAD

**Issue by pkerichang** [beached/daw_json_link#427]
In the popular C++ json library [nlohmann/json](https://github.com/nlohmann/json), in order to convert custom types, you can either define `to_json()` and `from_json()` in the same namespace as the type, or add a template specialization of `adl_serializer` like so:

```c++
// partial specialization (full specialization works too)
namespace nlohmann {
    template <typename T>
    struct adl_serializer<boost::optional<T>> {
        static void to_json(json& j, const boost::optional<T>& opt) {
            // ...
        }

        static void from_json(const json& j, boost::optional<T>& opt) {
            // ...
        }
    };
}
```

this is great for parsing/serializing third party types (where you don't want to hijack their namespace), or, in my example, I want to make all enums parse/serialilze by name.  Instead of defining `from_string()` and `to_string()` in every namespace for every enum I am using, with the [magic_enum](https://github.com/Neargye/magic_enum) library, I can just do something like:

```c++

// If adl_serializer exists in daw-json-link
namespace daw::json {
    template <typename T>
    struct adl_serializer<T, typename std::enable_if_t<std::is_enum_v<T>>> {
        constexpr std::string_view to_string(T obj) {
            return magic_enum::enum_name(obj);
        }

        constexpr T from_string(daw::tag_t<T>, std::string_view name) {
            auto test = magic_enum::enum_cast<T>(name);
            return *test;
        }
    };
}
```

Is there an equivalent feature in daw-json-link?

**Comment by beached** [comment]
This should be doable with the `daw:json::json_data_contract` trait for types.  Something like https://jsonlink.godbolt.org/z/495M3MsEf would allow any enum to be used as a string, the second param on the type can be used with enable_if/void_t if C++20 isn't available.

```cpp
#include <daw/json/daw_json_link.h>

#include <cstddef>
#include <magic_enum/magic_enum_all.hpp>
#include <string_view>
#include <type_traits>

namespace foo {
enum class Colours : std::uint8_t { Red, Green, Blue };

constexpr std::string_view to_string(auto E)
    requires(std::is_enum_v<decltype(E)>)
{
    return magic_enum::enum_name(E);
}

constexpr Colours from_string(daw::tag_t<Colours>, std::string_view sv) {
    return magic_enum::enum_cast<Colours>(sv).value();
}
}  // namespace foo

namespace daw::json {
template <typename E>
    requires std::is_enum_v<E>
struct json_data_contract<E> {
    using type = json_type_alias<json_custom_no_name<E>>;
};
}  // namespace daw::json


int main( ) {
    constexpr std::string_view json_doc = R"json("Red")json";

    return (int)daw::json::from_json<foo::Colours>( json_doc );
}
```

**Comment by pkerichang** [comment]
In the code you posted, the `to_string()` and `from_string()` is still defined in the same namespace as the enum (namespace `foo`).  So if I have two enums in different namespaces (`foo:Color` and `bar::Animal`, for example), I would still need to defined the `to_string()` and `from_string()` methods in both namespaces, right?  That's what I'm trying to avoid.

It's not a big deal if this is a limitation, I was just wondering if it is possible.

**Comment by beached** [comment]
I think I have overthought this, why can you not use the `json_data_contract` trait for your types/enums.  Is it that you want to support magic enum, or something else?

**Comment by beached** [comment]
Something like this will work without ADL or owning the type/polluting someone else's namespace.  https://jsonlink.godbolt.org/z/Efs8vx9ce

```cpp
#include <daw/json/daw_json_link.h>

#include <cstddef>
#include <magic_enum/magic_enum_all.hpp>
#include <string_view>
#include <type_traits>

namespace foo {
enum class Colours : std::uint8_t { Red, Green, Blue };
}  // namespace foo

template <typename Enum>
struct MagicEnumConverter {
    constexpr std::string_view operator()(Enum e) const
        requires(std::is_enum_v<Enum>)
    {
        return magic_enum::enum_name(e);
    }

    constexpr Enum operator()(std::string_view sv) const {
        return magic_enum::enum_cast<Enum>(sv).value();
    }
};

template <typename E>
    requires std::is_enum_v<E>
inline constexpr bool use_magic_enum_v = false;

template <>
inline constexpr bool use_magic_enum_v<foo::Colours> = true;

namespace daw::json {
template <typename E>
    requires use_magic_enum_v<E>
struct json_data_contract<E> {
    using type = json_type_alias<
        json_custom_no_name<E, MagicEnumConverter<E>, MagicEnumConverter<E>>>;
};
}  // namespace daw::json

int main() {
    constexpr std::string_view json_doc = R"json("Red")json";

    return (int)daw::json::from_json<foo::Colours>(json_doc);
}
```

I would be reluctant to set the default to all enums as there are a great many that use a numeric mapping or something else involving upper/lower case...

**Comment by pkerichang** [comment]
I see, this is exactly what I wanted, unfortunately I'm stuck with C++17, which doesn't have the `requires` feature,  I guess this won't be possible then?

I think it is up to the user to decide whether they want to blanket make all enums use name versus numeric mapping (for my application, I definitely do), but thanks for providing an example of how to customize individual enums.  Can you add this to the cookbook/documentation as I think this is very useful?  Thanks!

**Comment by beached** [comment]
It would work fine with a C++17 solution   

https://jsonlink.godbolt.org/z/h4E7T6ncq
```cpp
#include <daw/json/daw_json_link.h>

#include <cstddef>
#include <magic_enum/magic_enum_all.hpp>
#include <string_view>
#include <type_traits>

namespace foo {
enum class Colours : std::uint8_t { Red, Green, Blue };
}  // namespace foo

template <typename Enum>
struct MagicEnumConverter {
    static_assert(std::is_enum_v<Enum>, "Only enum types are supported");
    constexpr std::string_view operator()(Enum e) const {
        return magic_enum::enum_name(e);
    }

    constexpr Enum operator()(std::string_view sv) const {
        return magic_enum::enum_cast<Enum>(sv).value();
    }
};

template <typename E>
inline constexpr bool use_magic_enum_v = false;

template <>
inline constexpr bool use_magic_enum_v<foo::Colours> = true;

namespace daw::json {
template <typename E>
struct json_data_contract<E, std::enable_if_t<use_magic_enum_v<E>>> {
    using type = json_type_alias<
        json_custom_no_name<E, MagicEnumConverter<E>, MagicEnumConverter<E>>>;
};
}  // namespace daw::json

int main() {
    constexpr std::string_view json_doc = R"json("Red")json";

    return (int)daw::json::from_json<foo::Colours>(json_doc);
}
```

**Comment by beached** [comment]
I should add a cookbook entry for magic enum/other reflection solutions over enums

**Comment by pkerichang** [comment]
Hello,

I just want to point out that if we are using this approach to declare enum serialization procedure (instead of implementing from_string() and to_string() in the same namespace), then we need to use `json_class` instead of `json_custom` to refer to the enum fields.  This took me quite a while to debug and figure out, so we should clarify that in the documentation.

**Comment by beached** [comment]
Not sure I follow, which example is wrong?

**Comment by pkerichang** [comment]
In the coookbook, the enum example code look like:

```c++
namespace foo {
enum class Colours : std::uint8_t { Red, Green, Blue };

constexpr std::string_view to_string(Colours obj);
constexpr Colors from_string(std::string_view sv);
}  // namespace foo


struct test {
  Colours foo;
  int bar;

};


namespace daw::json {
struct json_data_contract<test> {
    using type = json_member_list<json_custom<"foo", Colours>, json_number<"bar", int>>;
    // ...
};
}  // namespace daw::json
```

where you use `json_custom<>` around the `foo` field so that it looks for `to_string()` and `from_string()` methods in the same namespace to serialize the enum.

If we are using the approach discussed here, then we need to write the code like:


```c++
namespace foo {
enum class Colours : std::uint8_t { Red, Green, Blue };
}  // namespace foo


struct test {
  Colours foo;
  int bar;

};

namespace daw::json {
struct json_data_contract<foo:Colours> {
    // add MagicEnum stuffs for Colours here
    // ...
};

struct json_data_contract<test> {
    using type = json_member_list<json_class<"foo", Colours>, json_number<"bar", int>>;
    // ...
};
}  // namespace daw::json
```

Specifically, we need to use `json_class<>` instead of `json_custom<>` around the `foo` field.

The code posted here is not wrong, but we need to update code converting data structures containing enums to migrate from `json_custom<>` to `json_class<>`.

**Comment by beached** [comment]
Good point.  Tired right now, but pretty sure that `using type = json_member_list<json_link<"foo", Colours>, json_link<"bar", int>>;` should do it too

**Comment by pkerichang** [comment]
what is the difference between link and class?

**Comment by beached** [comment]
`json_link` can generally figure out what it is and mapped types, which the enums are in our example, will just work, as do things that fullfill certain properties.  https://github.com/beached/daw_json_link/blob/release/docs/cookbook/mapping_deduction.md has the ordering.  Because the enums are mapped here, they will take priority over the default to use their underlying value.
