### ISSUE TITLE
Compilation problem on GCC 14.1 (Linux)

### ISSUE THREAD

**Issue by iwasz** [beached/daw_json_link#429]
Hey after upgrade to GCC 14.1 I get:

```
/usr/include/c++/14.1.1/type_traits:1204:52: error: non-constant condition for static assertion
```

If I change (remove stuff after noexcept) in `build/_deps/daw_utf_range-src/include/daw/utf8/unchecked.h`:

```cpp
constexpr octet_iterator base( ) const
		noexcept( std::is_nothrow_copy_constructible<octet_iterator>::value ) {
	return it;
}
```

to:

```cpp
constexpr octet_iterator base( ) const
		noexcept {
	return it;
}
```

then everything gets back to normal. Dunno if that's something on my side or on library's - any ideas? Thanks!

**Comment by beached** [comment]
I see that with gcc 14.1 in the tests.  I doubt it is your code.  Looking into it

**Comment by beached** [comment]
Interesting that with the same libstdc++, gcc 14.1 fails this and clang does not. But the type definitely is complete as it is checking `std::is_nothrow_copy_constructible<char const *>::value`

**Comment by iwasz** [comment]
I found this : https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100381 does it
help?

**Comment by beached** [comment]
Same thing catching, but how can a `char const *` be an incomplete type right?  Plus the code has compiled in constant expressions that would have checked that anyways.  I get they are trying to prevent ODR here.  Still looking to see if the error is wrong on the type and I have invalid code though

**Comment by beached** [comment]
I have a fix in the utf-range repo that will work around this. I am thinking it is a compiler issue but could not replicate a small example.  changing the `std::is_nothrow_copy_constructible<T>::value` to `std::is_nothrow_copy_constructibe_v<T>` works around the issue.

**Comment by beached** [comment]
This should be fixed now

**Comment by iwasz** [comment]
Thanks!
