### ISSUE TITLE
build failure on gcc 12 C++ 20

### ISSUE THREAD

**Issue by pauldreik** [beached/daw_json_link#454]
Using debian stable, with gcc 12.2.0 (currently [12.2.0-14](https://packages.debian.org/bookworm/g++-12)), I get the following build failure on commit 85f5f3f3d15a27fa000733f758b157d2267a74c8 :

```plain
~/code$ git clone https://github.com/beached/daw_json_link.git
~/code$ cd daw_json_link
~/code/daw_json_link$ CXX=g++-12 cmake -B build-gcc12-cpp20 -S .  -GNinja -DDAW_ENABLE_TESTING=On  -DCMAKE_CXX_STANDARD=20
~/code/daw_json_link$ ninja -C build-gcc12-cpp20

# snip....
code/daw_json_link/include/daw/json/impl/daw_json_allocator_wrapper.h:58:87: error: typename std::allocator_traits<_Alloc>::rebind_traits is not a template [-fpermissive]
   58 |                           typename std::allocator_traits<T>::template rebind_traits<U>::type );
      |                                                                                       ^~
/home/banan/code/daw_json_link/include/daw/json/impl/daw_json_req_helper.h:108:17: note: in definition of macro DAW_JSON_MAKE_REQ_TYPE_ALIAS_TRAIT2
```

Using gcc12+cpp17 works fine, as well as gcc11+cpp20

**Comment by beached** [comment]
This is confusing, it is a template.  http://eel.is/c++draft/allocator.traits#:~:text=rebind_traits

Do you have an example, I wonder if this is an issue with gcc 12

**Comment by pauldreik** [comment]
I just cloned the repo and then ran the cmake+build command above. All the code is in this repo. Or do I perhaps misunderstand what you mean?
I edited the text to show the clone command as well.

I reproduced the same error also on debian testing, using gcc 12.4.0. gcc 13 and 14 work fine.

**Comment by pauldreik** [comment]
I made a reproducer on godbolt:

```cpp
#include <memory>
#include <type_traits>

template <typename T, typename U>
inline constexpr bool allocator_has_rebind_v = requires {
    typename std::allocator_traits<T>::template rebind_traits<U>::type;
};
```

1. [gcc 11.3: fail with different error](https://godbolt.org/z/f6x4aq66n)
2. [ gcc 11.4: ok](https://godbolt.org/z/7a69Ynabx)
3. [gcc 12.1: fail](https://godbolt.org/z/fhGcGzjvo)
4. [gcc 12.2: fail](https://godbolt.org/z/aP6znE5dY)
5. [gcc 12.3: fail](https://godbolt.org/z/333c56eKd)
6. [gcc 12.4: fail](https://godbolt.org/z/rYz7EWb5Y)
7. [gcc 13.1: fail](https://godbolt.org/z/nK51shWdn)
8. [gcc 13.2: fail](https://godbolt.org/z/WdjYrnaKc)
9. [gcc 13.3: ok](https://godbolt.org/z/fcG9KoGx1)
10. [gcc 14.1: ok](https://godbolt.org/z/e1b6YG4K3)
11. [gcc 14.2: ok](https://godbolt.org/z/TWGcT718s)
12. [gcc trunk: ok](https://godbolt.org/z/o1WEzonnG)
13. [clang 19 libc++: ok](https://godbolt.org/z/bfafe1edj)
14. [clang 19 libstdc++: ok](https://godbolt.org/z/nrcdYKPxK)

**Comment by beached** [comment]
Glad they fixed it.   I am just testing, but I will add a compilation define for all of these that disables them and uses SFINAE/specialization, the pre-20 way.

**Comment by beached** [comment]
Should be fixed with https://github.com/beached/daw_json_link/commit/f7bf7018706228d63212d0d45eb5f207fe310f52

**Comment by pauldreik** [comment]
Thanks for fixing it! It now compiles.

I wonder - why was this not caught in CI? it seems like gcc 12 is tested with C++20.
EDIT: it **was** caught in CI: https://github.com/beached/daw_json_link/actions/runs/11529159711/job/32097261291

**Comment by beached** [comment]
https://github.com/beached/daw_json_link/releases/tag/v3.29.2
